require("plugins-setup")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.move")
require("plugins.nvim-lspconfig")
require("plugins.nvim-lint")
require("plugins.blamer")
require("plugins.prettier")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.treesitter-context")
require("core.options")
require("core.colorscheme")
require("core.keymaps")

