#!/bin/bash

## Created By Aditya Shakya
MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 6 -font "Fira Code Medium 9" <<< " Hibernate| Lock| Logout| Reboot| Suspend| Shutdown")"
            case "$MENU" in
                *Hibernate) systemctl hibernate ;;
                *Lock) i3lock-fancy ;;
                *Logout) i3-msg exit ;;
                *Reboot) systemctl reboot ;;
                *Suspend) systemctl suspend ;;
                *Shutdown) systemctl -i poweroff
            esac
